# Generated by Django 3.0.5 on 2020-04-23 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=150, null=True)),
                ('prof_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartMeters',
            fields=[
                ('SER', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('device_status', models.PositiveSmallIntegerField(choices=[(1, 'working'), (0, 'not_working')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_monitor_app.Clint')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(default=0.0)),
                ('bill', models.FloatField(default=0.0)),
                ('conception_date', models.DateTimeField(null=True)),
                ('price_category', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_monitor_app.Clint')),
            ],
            options={
                'ordering': ['consumption'],
            },
        ),
    ]
