# Generated by Django 3.0.5 on 2020-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clint',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clint',
            name='prof_image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to=''),
        ),
    ]
