# Generated by Django 3.0.5 on 2020-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_monitor_app', '0002_auto_20200430_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clint',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
