# Generated by Django 3.0.5 on 2020-04-30 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_monitor_app', '0005_auto_20200430_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliances',
            options={'ordering': ['appliance_category']},
        ),
        migrations.AlterField(
            model_name='appliances',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
