# Generated by Django 3.0.7 on 2020-06-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_monitor_app', '0008_auto_20200603_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clint',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clint',
            name='second_name',
        ),
        migrations.AddField(
            model_name='smartmeters',
            name='consumption',
            field=models.FloatField(default=0.0),
        ),
    ]
