# Generated by Django 3.0.7 on 2020-06-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_monitor_app', '0009_auto_20200615_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeters',
            name='conception_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
